### ISSUE TITLE
block.io is a scam! they took my money and they never respond to emails.

### ISSUE THREAD

**Issue by LinuxCs** [BlockIo/blockio-basic-multisig-sweep#3]
they suspended my accounts ,, freezes my funds and when i tried to sweep it using the keys they provided i didn't success and even their  SoChain's V3 api is now paid!  imagine that now they want me to pay 129$ to withdraw my 450$  

i advice all the developers to never trust block.io they are thief's 

even when i tried to decrypt the bip32 keys to extract my wallets i couldn't make it work

really i don't care if you took the money but i'll share my experience with everybody all over the internet

**Comment by olamigokayphils** [comment]
@LinuxCs I hope your Keys were backed up?
Use this Instead https://github.com/olamigokayphils/blockio-multisig-sweep
